Turku theme fixes
City-of-Turku/kerrokantasi-ui-turku pull request #5
Opened 2019-06-17 12:18 UTC by juhakujala

* Update styles and style variables
* Change turku logo files to correct ones
* Use turku primary color on the default-image.svg
* Add new turku specific translation strings
* Remove unecessary images

2019-06-17 18:03 UTC, frwickst requested changes
Overall everything looks good, but the imports look a bit strange to me. Even if it for some reason works, I see no reason to have the `_` in there, or is there a good reason for it?

2019-06-17 18:03 UTC, frwickst commented on assets/sass/app.scss
> +@import "turku/navigation";
Does this work even if the file is called _navigation.scss?

2019-06-17 18:03 UTC, frwickst commented on assets/sass/app.scss
> +@import "turku/labels";
Does this work even if the file is called _labels.scss?

2019-06-18 05:33 UTC, juhakujala commented
> Overall everything looks good, but the imports look a bit strange to me. Even if it for some reason works, I see no reason to have the `_` in there, or is there a good reason for it?

They do work. It's a convention that is also used in the kerrokantasi-ui repository now. The `_` implies that the file is sort of a component or a minor part of the styles. Same convention can be found from the bootstrap repository. https://github.com/twbs/bootstrap/tree/master/scss

2019-06-19 11:44 UTC, frwickst approved these changes

2019-06-19 11:44 UTC, merged